[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
lines_after_imports = 2

sections = "FUTURE,STDLIB,THIRDPARTY,DJANGO,FIRSTPARTY,LOCALFOLDER"

known_django = ["django", "django.contrib"]

known_first_party = ["api", "api_yamdb", "reviews", "users"]
