# Generated by Django 5.1.1 on 2025-09-10 22:04

import django.core.validators
from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yamdbuser',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='биография'),
        ),
        migrations.AlterField(
            model_name='yamdbuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='yamdbuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[users.validators.UsernameValidator()], verbose_name='username'),
        ),
    ]
