# Generated by Django 5.1.1 on 2025-09-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_yamdbuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yamdbuser',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='биография'),
        ),
    ]
