# Generated by Django 5.1.1 on 2025-09-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_yamdbuser_bio_alter_yamdbuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yamdbuser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='код подтверждения'),
        ),
    ]
