# Generated by Django 5.1.1 on 2025-09-10 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_yamdbuser_confirmation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yamdbuser',
            name='confirmation_code',
        ),
    ]
