# Generated by Django 5.1.1 on 2025-09-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_alter_title_genre_alter_title_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.IntegerField(default=1, verbose_name='Рейтинг'),
        ),
    ]
